version: "3.6"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_todo
    volumes:
      - ./:/source
      - /source/node_modules
    command: yarn start
    ports:
      - "3000:3000"
    restart: always